kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volume
  namespace: hexagonal-test
  labels:
    type: local
    app: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/data/jenkins"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc-claim
  namespace: hexagonal-test
  labels:
    app: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi