postgresqlPostgresPassword: hexagonalrootPassword
postgresqlUsername: hexagonaluser

## PostgreSQL password
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
##
postgresqlPassword: hexagonaluserPassword

## PostgreSQL password using existing secret
## existingSecret: secret
##

## Mount PostgreSQL secret as a file instead of passing environment variable
# usePasswordFile: false

## Create a database
## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run
##
postgresqlDatabase: hexagonaldb

persistence:
  enabled: false
  existingClaim: postgres-pv-claim
  mountPath: /var/lib/postgresql/data